[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Fall Night"

[colors]
foreground = "#ccbeb3"
background = "#1a1818"
cursor_bg = "#e0a66d"
cursor_border = "#e0a66d"
cursor_fg = "#1a1818"
selection_bg = "#2d2926"
selection_fg = "#ccbeb3"
split = "#e0a66d"
compose_cursor = "#c57054"
scrollbar_thumb = "#ae9685"

ansi = [
  "#262423", # black
  "#c0603f", # dark_red
  "#7a895c", # dark_green
  "#ef9e74", # dark_yellow
  "#a4a0df", # dark_blue
  "#d2acc3", # dark_magenta
  "#6a9b86", # dark_cyan
  "#ae9685" # light_gray
]

brights = [
  "#665c54", # gray
  "#c57054", # red
  "#a6bc90", # green
  "#e0a66d", # yellow
  "#90acd5", # blue
  "#c4b2d1", # magenta
  "#7fb395", # cyan
  "#ccbeb3" # white
]

[colors.tab_bar]
inactive_tab_edge = "#0f0e0e"
background = "#1a1818"

[colors.tab_bar.active_tab]
fg_color = "#1a1818"
bg_color = "#e0a66d"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#1a1818"
bg_color = "#665c54"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#1a1818"
bg_color = "#262423"

[colors.tab_bar.new_tab]
fg_color = "#1a1818"
bg_color = "#a6bc90"

[colors.tab_bar.new_tab_hover]
fg_color = "#1a1818"
bg_color = "#262423"
intensity = "Bold"
