[metadata]
author = "Black Atom Industries"
name = "Black Atom — JPN ∷ Murasaki Yoru"

[colors]
foreground = "#D4BFD6"
background = "#332031"
cursor_bg = "#e6a319"
cursor_border = "#e6a319"
cursor_fg = "#332031"
selection_bg = "#573954"
selection_fg = "#D4BFD6"
split = "#e6a319"
compose_cursor = "#F0635C"
scrollbar_thumb = "#946996"

ansi = [
  "#462c43", # black
  "#ec362d", # dark_red
  "#4DB58A", # dark_green
  "#FE9B16", # dark_yellow
  "#39a6cd", # dark_blue
  "#7E5BA2", # dark_magenta
  "#6fa9a8", # dark_cyan
  "#946996" # light_gray
]

brights = [
  "#7d5178", # gray
  "#F0635C", # red
  "#6dc29f", # green
  "#e6a319", # yellow
  "#71c0db", # blue
  "#EC6EAA", # magenta
  "#8FBCBB", # cyan
  "#D4BFD6" # white
]

[colors.tab_bar]
inactive_tab_edge = "#20141f"
background = "#332031"

[colors.tab_bar.active_tab]
fg_color = "#332031"
bg_color = "#e6a319"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#332031"
bg_color = "#6d4769"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#332031"
bg_color = "#462c43"

[colors.tab_bar.new_tab]
fg_color = "#332031"
bg_color = "#6dc29f"

[colors.tab_bar.new_tab_hover]
fg_color = "#332031"
bg_color = "#462c43"
intensity = "Bold"
