[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Summer Day"

[colors]
foreground = "#343e4d"
background = "#d1d6e1"
cursor_bg = "#dca958"
cursor_border = "#dca958"
cursor_fg = "#d1d6e1"
selection_bg = "#e0e4eb"
selection_fg = "#343e4d"
split = "#dca958"
compose_cursor = "#dd7e5d"
scrollbar_thumb = "#506d95"

ansi = [
  "#3e4b5c", # black
  "#ca6d4c", # dark_red
  "#729e60", # dark_green
  "#e3913d", # dark_yellow
  "#5c72d6", # dark_blue
  "#8253c5", # dark_magenta
  "#619f80", # dark_cyan
  "#b7beca" # light_gray
]

brights = [
  "#5979a6", # gray
  "#dd7e5d", # red
  "#72ae6a", # green
  "#dca958", # yellow
  "#578fdc", # blue
  "#c65295", # magenta
  "#7bb7a4", # cyan
  "#d1d6e1" # white
]

[colors.tab_bar]
inactive_tab_edge = "#c6cbd5"
background = "#d1d6e1"

[colors.tab_bar.active_tab]
fg_color = "#d1d6e1"
bg_color = "#dca958"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#d1d6e1"
bg_color = "#7b94b8"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d1d6e1"
bg_color = "#b7beca"

[colors.tab_bar.new_tab]
fg_color = "#d1d6e1"
bg_color = "#72ae6a"

[colors.tab_bar.new_tab_hover]
fg_color = "#d1d6e1"
bg_color = "#b7beca"
intensity = "Bold"
