[metadata]
author = "Black Atom Industries"
name = "Black Atom — STA ∷ Operations"

[colors]
foreground = "#c1efd5"
background = "#21302d"
cursor_bg = "#b7db6e"
cursor_border = "#b7db6e"
cursor_fg = "#21302d"
selection_bg = "#354e46"
selection_fg = "#c1efd5"
split = "#b7db6e"
compose_cursor = "#f08cb4"
scrollbar_thumb = "#9bdebe"

ansi = [
  "#293c36", # black
  "#eb7aa8", # dark_red
  "#5dba5d", # dark_green
  "#e9b565", # dark_yellow
  "#91bcad", # dark_blue
  "#a2b0e0", # dark_magenta
  "#59bf84", # dark_cyan
  "#91bcad" # light_gray
]

brights = [
  "#5b8972", # gray
  "#f08cb4", # red
  "#80c980", # green
  "#b7db6e", # yellow
  "#abe7ca", # blue
  "#b6bee0", # magenta
  "#75d69e", # cyan
  "#c1efd5" # white
]

[colors.tab_bar]
inactive_tab_edge = "#192323"
background = "#21302d"

[colors.tab_bar.active_tab]
fg_color = "#21302d"
bg_color = "#b7db6e"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#21302d"
bg_color = "#51796d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#21302d"
bg_color = "#293c36"

[colors.tab_bar.new_tab]
fg_color = "#21302d"
bg_color = "#80c980"

[colors.tab_bar.new_tab_hover]
fg_color = "#21302d"
bg_color = "#293c36"
intensity = "Bold"
