[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Fall Day"

[colors]
foreground = "#232323"
background = "#e4decd"
cursor_bg = "#d19845"
cursor_border = "#d19845"
cursor_fg = "#e4decd"
selection_bg = "#eeeadf"
selection_fg = "#232323"
split = "#d19845"
compose_cursor = "#dd7e5d"
scrollbar_thumb = "#665c54"

ansi = [
  "#2c2928", # black
  "#ca6d4c", # dark_red
  "#4a7126", # dark_green
  "#cc764b", # dark_yellow
  "#3d668e", # dark_blue
  "#ab80a8", # dark_magenta
  "#296a50", # dark_cyan
  "#ccc5b2" # light_gray
]

brights = [
  "#7c6f64", # gray
  "#dd7e5d", # red
  "#58852c", # green
  "#d19845", # yellow
  "#5980a6", # blue
  "#a58bc1", # magenta
  "#348764", # cyan
  "#e4decd" # white
]

[colors.tab_bar]
inactive_tab_edge = "#d7d2c3"
background = "#e4decd"

[colors.tab_bar.active_tab]
fg_color = "#e4decd"
bg_color = "#d19845"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e4decd"
bg_color = "#928374"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e4decd"
bg_color = "#ccc5b2"

[colors.tab_bar.new_tab]
fg_color = "#e4decd"
bg_color = "#58852c"

[colors.tab_bar.new_tab_hover]
fg_color = "#e4decd"
bg_color = "#ccc5b2"
intensity = "Bold"
