[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Winter Day"

[colors]
foreground = "#1d272c"
background = "#d4dade"
cursor_bg = "#d19845"
cursor_border = "#d19845"
cursor_fg = "#d4dade"
selection_bg = "#e2e6e9"
selection_fg = "#1d272c"
split = "#d19845"
compose_cursor = "#dd7e5d"
scrollbar_thumb = "#475e6a"

ansi = [
  "#212c31", # black
  "#ca6d4c", # dark_red
  "#4a7126", # dark_green
  "#cc764b", # dark_yellow
  "#3d668e", # dark_blue
  "#ab80a8", # dark_magenta
  "#296a50", # dark_cyan
  "#b6c2c9" # light_gray
]

brights = [
  "#516c7a", # gray
  "#dd7e5d", # red
  "#58852c", # green
  "#d19845", # yellow
  "#5980a6", # blue
  "#a58bc1", # magenta
  "#348764", # cyan
  "#d4dade" # white
]

[colors.tab_bar]
inactive_tab_edge = "#c5ced3"
background = "#d4dade"

[colors.tab_bar.active_tab]
fg_color = "#d4dade"
bg_color = "#d19845"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#d4dade"
bg_color = "#5b7988"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d4dade"
bg_color = "#b6c2c9"

[colors.tab_bar.new_tab]
fg_color = "#d4dade"
bg_color = "#58852c"

[colors.tab_bar.new_tab_hover]
fg_color = "#d4dade"
bg_color = "#b6c2c9"
intensity = "Bold"
