[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Winter Night"

[colors]
foreground = "#cdd6e4"
background = "#212225"
cursor_bg = "#d3b17a"
cursor_border = "#d3b17a"
cursor_fg = "#212225"
selection_bg = "#34363b"
selection_fg = "#cdd6e4"
split = "#d3b17a"
compose_cursor = "#b86a6a"
scrollbar_thumb = "#a6afc1"

ansi = [
  "#2c2d30", # black
  "#a65959", # dark_red
  "#507765", # dark_green
  "#eba778", # dark_yellow
  "#94acb8", # dark_blue
  "#b793b7", # dark_magenta
  "#568383", # dark_cyan
  "#a6afc1" # light_gray
]

brights = [
  "#5b6171", # gray
  "#b86a6a", # red
  "#5e9e8b", # green
  "#d3b17a", # yellow
  "#8c9bc2", # blue
  "#c8adc8", # magenta
  "#67a5a5", # cyan
  "#cdd6e4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#18191b"
background = "#212225"

[colors.tab_bar.active_tab]
fg_color = "#212225"
bg_color = "#d3b17a"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#212225"
bg_color = "#454955"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#212225"
bg_color = "#2c2d30"

[colors.tab_bar.new_tab]
fg_color = "#212225"
bg_color = "#5e9e8b"

[colors.tab_bar.new_tab_hover]
fg_color = "#212225"
bg_color = "#2c2d30"
intensity = "Bold"
