[metadata]
author = "Black Atom Industries"
name = "Black Atom — CRB ∷ SUPR"

[colors]
foreground = "#2d3237"
background = "#f2f4f9"
cursor_bg = "#ff8129"
cursor_border = "#ff8129"
cursor_fg = "#f2f4f9"
selection_bg = "#dee6ed"
selection_fg = "#2d3237"
split = "#ff8129"
compose_cursor = "#ff5533"
scrollbar_thumb = "#444c54"

ansi = [
  "#2d3237", # black
  "#e63c19", # dark_red
  "#617283", # dark_green
  "#ff7140", # dark_yellow
  "#7a8c9d", # dark_blue
  "#617283", # dark_magenta
  "#363d43", # dark_cyan
  "#92a9bb" # light_gray
]

brights = [
  "#617283", # gray
  "#ff5533", # red
  "#7a8c9d", # green
  "#ff8129", # yellow
  "#92a9bb", # blue
  "#7a8c9d", # magenta
  "#2d3237", # cyan
  "#dee6ed" # white
]

[colors.tab_bar]
inactive_tab_edge = "#e8eff2"
background = "#f2f4f9"

[colors.tab_bar.active_tab]
fg_color = "#e8eff2"
bg_color = "#ff8129"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e8eff2"
bg_color = "#7a8c9d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e8eff2"
bg_color = "#dee6ed"

[colors.tab_bar.new_tab]
fg_color = "#e8eff2"
bg_color = "#7a8c9d"

[colors.tab_bar.new_tab_hover]
fg_color = "#e8eff2"
bg_color = "#dee6ed"
intensity = "Bold"
