[metadata]
author = "Black Atom Industries"
name = "Black Atom — STA ∷ Engineering"

[colors]
foreground = "#d5f4e3"
background = "#192422"
cursor_bg = "#b7db6e"
cursor_border = "#b7db6e"
cursor_fg = "#192422"
selection_bg = "#2d423b"
selection_fg = "#d5f4e3"
split = "#b7db6e"
compose_cursor = "#f08cb4"
scrollbar_thumb = "#b2e5cd"

ansi = [
  "#21302b", # black
  "#eb7aa8", # dark_red
  "#5dba5d", # dark_green
  "#e9b565", # dark_yellow
  "#91bcad", # dark_blue
  "#8b9dd8", # dark_magenta
  "#59bf84", # dark_cyan
  "#91bcad" # light_gray
]

brights = [
  "#5b8972", # gray
  "#f08cb4", # red
  "#80c980", # green
  "#b7db6e", # yellow
  "#c3eed9", # blue
  "#9baae6", # magenta
  "#75d69e", # cyan
  "#d5f4e3" # white
]

[colors.tab_bar]
inactive_tab_edge = "#151d1d"
background = "#192422"

[colors.tab_bar.active_tab]
fg_color = "#192422"
bg_color = "#b7db6e"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#192422"
bg_color = "#51796d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#192422"
bg_color = "#21302b"

[colors.tab_bar.new_tab]
fg_color = "#192422"
bg_color = "#80c980"

[colors.tab_bar.new_tab_hover]
fg_color = "#192422"
bg_color = "#21302b"
intensity = "Bold"
