[colors]
foreground = "#C5C9C7"
background = "#14171d"

cursor_bg = "#C5C9C7"
cursor_fg = "#14171d"
cursor_border = "#C5C9C7"

selection_fg = "#C5C9C7"
selection_bg = "#393B42"

scrollbar_thumb = "#393B42"
split = "#393B42"

ansi = [
  "#14171d",
  "#C4746E",
  "#8A9A7B",
  "#C4B28A",
  "#8BA4B0",
  "#A292A3",
  "#8EA4A2",
  "#A4A7A4",
]
brights = [
  "#A4A7A4",
  "#E46876",
  "#87A987",
  "#E6C384",
  "#7FB4CA",
  "#938AA9",
  "#7AA89F",
  "#C5C9C7",
]

[colors.tab_bar]
inactive_tab_edge = "#0f1218"
background = "#0f1218"

[colors.tab_bar.active_tab]
fg_color = "#14171d"
bg_color = "#E6C384"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#14171d"
bg_color = "#A4A7A4"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#14171d"
bg_color = "#21242a"

[colors.tab_bar.new_tab]
fg_color = "#14171d"
bg_color = "#8BA4B0"

[colors.tab_bar.new_tab_hover]
fg_color = "#14171d"
bg_color = "#8EA4A2"
intensity = "Bold"

[metadata]
name = "kanso-ink"
aliases = ["kansoink", "kanso_ink"]
author = "nikbrunner"
