[colors]
foreground = "#C5C9C7"
background = "#090E13"

cursor_bg = "#C5C9C7"
cursor_fg = "#090E13"
cursor_border = "#C5C9C7"

selection_fg = "#C5C9C7"
selection_bg = "#24262D"

scrollbar_thumb = "#24262D"
split = "#24262D"

ansi = [
  "#090E13",
  "#C4746E",
  "#8A9A7B",
  "#C4B28A",
  "#8BA4B0",
  "#A292A3",
  "#8EA4A2",
  "#A4A7A4",
]
brights = [
  "#A4A7A4",
  "#E46876",
  "#87A987",
  "#E6C384",
  "#7FB4CA",
  "#938AA9",
  "#7AA89F",
  "#C5C9C7",
]

[colors.tab_bar]
inactive_tab_edge = "#060A0F"
background = "#060A0F"

[colors.tab_bar.active_tab]
fg_color = "#090E13"
bg_color = "#E6C384"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#090E13"
bg_color = "#A4A7A4"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#090E13"
bg_color = "#1A1C23"

[colors.tab_bar.new_tab]
fg_color = "#090E13"
bg_color = "#87A987"

[colors.tab_bar.new_tab_hover]
fg_color = "#090E13"
bg_color = "#1A1C23"
intensity = "Bold"

[metadata]
name = "kanso-zen"
aliases = ["kansozen", "kanso_zen"]
author = "nikbrunner"
